asp_presentacion/Pages/Ventanas/Artistas.cshtml.cs
using lib_dominio.Entidades;
using lib_dominio.Nucleo;
using lib_presentaciones.Interfaces;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
namespace asp_presentacion.Pages.Ventanas
{
    public class ArtistasModel : PageModel
    {
        private IArtistasPresentacion? iPresentacion = null;

        public ArtistasModel(IArtistasPresentacion iPresentacion)
        {
            try
            {
                this.iPresentacion = iPresentacion;
                Filtro = new Artistas();
            }
            catch (Exception ex)
            {
                LogConversor.Log(ex, ViewData!);
            }
        }

        public IFormFile? FormFile { get; set; }
        [BindProperty] public Enumerables.Ventanas Accion { get; set; }
        [BindProperty] public Artistas? Actual { get; set; }
        [BindProperty] public Artistas? Filtro { get; set; }
        [BindProperty] public List<Artistas>? Lista { get; set; }
        public virtual void OnGet() { OnPostBtRefrescar(); }

        public void OnPostBtRefrescar()
        {
            try
            {
                //var variable_session = HttpContext.Session.GetString("Usuario");
                //if (String.IsNullOrEmpty(variable_session))
                //{
                //    HttpContext.Response.Redirect("/");
                //    return;
                //}
                Filtro!.NombreArtista = Filtro!.NombreArtista ?? "";
                Accion = Enumerables.Ventanas.Listas;
                var task = this.iPresentacion!.PorNombreArtista(Filtro!);
                task.Wait();
                Lista = task.Result;
                Actual = null;
            }
            catch (Exception ex)
            {
                LogConversor.Log(ex, ViewData!);
            }
        }

        public virtual void OnPostBtNuevo()
        {
            try
            {
                Accion = Enumerables.Ventanas.Editar;
                Actual = new Artistas();
            }
            catch (Exception ex)
            {
                LogConversor.Log(ex, ViewData!);
            }
        }

        public virtual void OnPostBtModificar(string data)
        {
            try
            {
                OnPostBtRefrescar();
                Accion = Enumerables.Ventanas.Editar;
                Actual = Lista!.FirstOrDefault(x => x.ArtistaId.ToString() == data);
            }
            catch (Exception ex)
            {
                LogConversor.Log(ex, ViewData!);
            }
        }

        public virtual void OnPostBtGuardar()
        {
            try
            {
                Accion = Enumerables.Ventanas.Editar;
                Task<Artistas>? task = null;
                if (Actual!.ArtistaId == 0)
                    task = this.iPresentacion!.Guardar(Actual!)!;
                else
                    task = this.iPresentacion!.Modificar(Actual!)!;
                task.Wait();
                Actual = task.Result;
                Accion = Enumerables.Ventanas.Listas;
                OnPostBtRefrescar();
            }
            catch (Exception ex)
            {
                LogConversor.Log(ex, ViewData!);
            }
        }

        public virtual void OnPostBtBorrarVal(string data)
        {
            try
            {
                OnPostBtRefrescar();
                Accion = Enumerables.Ventanas.Borrar;
                Actual = Lista!.FirstOrDefault(x => x.ArtistaId.ToString() == data);
            }
            catch (Exception ex)
            {
                LogConversor.Log(ex, ViewData!);
            }
        }

        public virtual void OnPostBtBorrar()
        {
            try
            {
                var task = this.iPresentacion!.Borrar(Actual!);
                Actual = task.Result;
                OnPostBtRefrescar();
            }
            catch (Exception ex)
            {
                LogConversor.Log(ex, ViewData!);
            }
        }

        public void OnPostBtCancelar()
        {
            try
            {
                Accion = Enumerables.Ventanas.Listas;
                OnPostBtRefrescar();
            }
            catch (Exception ex)
            {
                LogConversor.Log(ex, ViewData!);
            }
        }

        public void OnPostBtCerrar()
        {
            try
            {
                if (Accion == Enumerables.Ventanas.Listas)
                    OnPostBtRefrescar();
            }
            catch (Exception ex)
            {
                LogConversor.Log(ex, ViewData!);
            }
        }
    }
}

asp_presentacion/Pages/Ventanas/Clientes.cshtml.cs
using lib_dominio.Entidades;
using lib_dominio.Nucleo;
using lib_presentaciones.Interfaces;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
namespace asp_presentacion.Pages.Ventanas
{
    public class ClientesModel : PageModel
    {
        private IClientesPresentacion? iPresentacion = null;

        public ClientesModel(IClientesPresentacion iPresentacion)
        {
            try
            {
                this.iPresentacion = iPresentacion;
                Filtro = new Clientes();
            }
            catch (Exception ex)
            {
                LogConversor.Log(ex, ViewData!);
            }
        }

        public IFormFile? FormFile { get; set; }
        [BindProperty] public Enumerables.Ventanas Accion { get; set; }
        [BindProperty] public Clientes? Actual { get; set; }
        [BindProperty] public Clientes? Filtro { get; set; }
        [BindProperty] public List<Clientes>? Lista { get; set; }
        public virtual void OnGet() { OnPostBtRefrescar(); }

        public void OnPostBtRefrescar()
        {
            try
            {
                //var variable_session = HttpContext.Session.GetString("Usuario");
                //if (String.IsNullOrEmpty(variable_session))
                //{
                //    HttpContext.Response.Redirect("/");
                //    return;
                //}
                Filtro!.Nombre = Filtro!.Nombre ?? "";
                Accion = Enumerables.Ventanas.Listas;
                var task = this.iPresentacion!.PorNombre(Filtro!);
                task.Wait();
                Lista = task.Result;
                Actual = null;
            }
            catch (Exception ex)
            {
                LogConversor.Log(ex, ViewData!);
            }
        }

        public virtual void OnPostBtNuevo()
        {
            try
            {
                Accion = Enumerables.Ventanas.Editar;
                Actual = new Clientes();
            }
            catch (Exception ex)
            {
                LogConversor.Log(ex, ViewData!);
            }
        }

        public virtual void OnPostBtModificar(string data)
        {
            try
            {
                OnPostBtRefrescar();
                Accion = Enumerables.Ventanas.Editar;
                Actual = Lista!.FirstOrDefault(x => x.ClienteId.ToString() == data);
            }
            catch (Exception ex)
            {
                LogConversor.Log(ex, ViewData!);
            }
        }

        public virtual void OnPostBtGuardar()
        {
            try
            {
                Accion = Enumerables.Ventanas.Editar;
                Task<Clientes>? task = null;
                if (Actual!.ClienteId == 0)
                    task = this.iPresentacion!.Guardar(Actual!)!;
                else
                    task = this.iPresentacion!.Modificar(Actual!)!;
                task.Wait();
                Actual = task.Result;
                Accion = Enumerables.Ventanas.Listas;
                OnPostBtRefrescar();
            }
            catch (Exception ex)
            {
                LogConversor.Log(ex, ViewData!);
            }
        }

        public virtual void OnPostBtBorrarVal(string data)
        {
            try
            {
                OnPostBtRefrescar();
                Accion = Enumerables.Ventanas.Borrar;
                Actual = Lista!.FirstOrDefault(x => x.ClienteId.ToString() == data);
            }
            catch (Exception ex)
            {
                LogConversor.Log(ex, ViewData!);
            }
        }

        public virtual void OnPostBtBorrar()
        {
            try
            {
                var task = this.iPresentacion!.Borrar(Actual!);
                Actual = task.Result;
                OnPostBtRefrescar();
            }
            catch (Exception ex)
            {
                LogConversor.Log(ex, ViewData!);
            }
        }

        public void OnPostBtCancelar()
        {
            try
            {
                Accion = Enumerables.Ventanas.Listas;
                OnPostBtRefrescar();
            }
            catch (Exception ex)
            {
                LogConversor.Log(ex, ViewData!);
            }
        }

        public void OnPostBtCerrar()
        {
            try
            {
                if (Accion == Enumerables.Ventanas.Listas)
                    OnPostBtRefrescar();
            }
            catch (Exception ex)
            {
                LogConversor.Log(ex, ViewData!);
            }
        }
    }
}

asp_presentacion/Pages/Ventanas/DetallePedidos.cshtml.cs
using lib_dominio.Entidades;
using lib_dominio.Nucleo;
using lib_presentaciones.Interfaces;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
namespace asp_presentacion.Pages.Ventanas
{
    public class DetallePedidosModel : PageModel
    {
        private IDetallePedidosPresentacion? iPresentacion = null;

        public DetallePedidosModel(IDetallePedidosPresentacion iPresentacion)
        {
            try
            {
                this.iPresentacion = iPresentacion;
                Filtro = new DetallePedidos();
            }
            catch (Exception ex)
            {
                LogConversor.Log(ex, ViewData!);
            }
        }

        public IFormFile? FormFile { get; set; }
        [BindProperty] public Enumerables.Ventanas Accion { get; set; }
        [BindProperty] public DetallePedidos? Actual { get; set; }
        [BindProperty] public DetallePedidos? Filtro { get; set; }
        [BindProperty] public List<DetallePedidos>? Lista { get; set; }
        public virtual void OnGet() { OnPostBtRefrescar(); }

        public void OnPostBtRefrescar()
        {
            try
            {
                //    //var variable_session = HttpContext.Session.GetString("Usuario");
                //    //if (String.IsNullOrEmpty(variable_session))
                //    //{
                //    //    HttpContext.Response.Redirect("/");
                //    //    return;
                //    //}
                //    Filtro!.Titulo = Filtro!.Titulo ?? "";
                Accion = Enumerables.Ventanas.Listas;
                var task = this.iPresentacion!.Listar();
                task.Wait();
                Lista = task.Result;
                Actual = null;
            }
            catch (Exception ex)
            {
                LogConversor.Log(ex, ViewData!);
            }
        }

        public virtual void OnPostBtNuevo()
        {
            try
            {
                Accion = Enumerables.Ventanas.Editar;
                Actual = new DetallePedidos();
            }
            catch (Exception ex)
            {
                LogConversor.Log(ex, ViewData!);
            }
        }

        public virtual void OnPostBtModificar(string data)
        {
            try
            {
                OnPostBtRefrescar();
                Accion = Enumerables.Ventanas.Editar;
                Actual = Lista!.FirstOrDefault(x => x.DetallesId.ToString() == data);
            }
            catch (Exception ex)
            {
                LogConversor.Log(ex, ViewData!);
            }
        }

        public virtual void OnPostBtGuardar()
        {
            try
            {
                Accion = Enumerables.Ventanas.Editar;
                Task<DetallePedidos>? task = null;
                if (Actual!.DetallesId == 0)
                    task = this.iPresentacion!.Guardar(Actual!)!;
                else
                    task = this.iPresentacion!.Modificar(Actual!)!;
                task.Wait();
                Actual = task.Result;
                Accion = Enumerables.Ventanas.Listas;
                OnPostBtRefrescar();
            }
            catch (Exception ex)
            {
                LogConversor.Log(ex, ViewData!);
            }
        }

        public virtual void OnPostBtBorrarVal(string data)
        {
            try
            {
                OnPostBtRefrescar();
                Accion = Enumerables.Ventanas.Borrar;
                Actual = Lista!.FirstOrDefault(x => x.DetallesId.ToString() == data);
            }
            catch (Exception ex)
            {
                LogConversor.Log(ex, ViewData!);
            }
        }

        public virtual void OnPostBtBorrar()
        {
            try
            {
                var task = this.iPresentacion!.Borrar(Actual!);
                Actual = task.Result;
                OnPostBtRefrescar();
            }
            catch (Exception ex)
            {
                LogConversor.Log(ex, ViewData!);
            }
        }

        public void OnPostBtCancelar()
        {
            try
            {
                Accion = Enumerables.Ventanas.Listas;
                OnPostBtRefrescar();
            }
            catch (Exception ex)
            {
                LogConversor.Log(ex, ViewData!);
            }
        }

        public void OnPostBtCerrar()
        {
            try
            {
                if (Accion == Enumerables.Ventanas.Listas)
                    OnPostBtRefrescar();
            }
            catch (Exception ex)
            {
                LogConversor.Log(ex, ViewData!);
            }
        }
    }
}

asp_presentacion/Pages/Ventanas/Artistas.cshtml
@page
@model asp_presentacion.Pages.Ventanas.ArtistasModel
@{
    ViewData["Titulo"] = "Gestión de Artistas";
}

<div class="container-fluid py-4">
    <form method="POST" enctype="multipart/form-data">
        @Html.AntiForgeryToken()

        <div class="d-flex justify-content-between align-items-center page-header">
            <h2 class="text-primary mb-0"><i class="fas fa-microphone-lines"></i>Artistas</h2>

            <div class="action-bar">
                <button type="submit" asp-page-handler="BtRefrescar"
                        class="btn btn-outline-primary btn-icon"
                        disabled="@(Model.Accion != lib_dominio.Nucleo.Enumerables.Ventanas.Listas)">
                    <i class="fas fa-sync-alt"></i> Refrescar
                </button>

                <button type="submit" asp-page-handler="BtNuevo"
                        class="btn btn-success btn-icon"
                        disabled="@(Model.Accion != lib_dominio.Nucleo.Enumerables.Ventanas.Listas)">
                    <i class="fas fa-plus"></i> Nuevo
                </button>

                <button type="submit" asp-page-handler="BtGuardar"
                        class="btn btn-primary btn-icon"
                        disabled="@(Model.Accion == lib_dominio.Nucleo.Enumerables.Ventanas.Listas)">
                    <i class="fas fa-save"></i> Guardar
                </button>

                <button type="submit" asp-page-handler="BtCancelar"
                        class="btn btn-secondary btn-icon"
                        disabled="@(Model.Accion == lib_dominio.Nucleo.Enumerables.Ventanas.Listas)">
                    <i class="fas fa-times"></i> Cancelar
                </button>
            </div>
        </div>

        @if (Model.Accion != lib_dominio.Nucleo.Enumerables.Ventanas.Listas ||
                Model.Accion == lib_dominio.Nucleo.Enumerables.Ventanas.Borrar)
        {
            <input type="hidden" asp-for="@Model.Actual!.ArtistaId" />
        }
        @if (Model.Accion == lib_dominio.Nucleo.Enumerables.Ventanas.Borrar)
        {
            <input type="hidden" asp-for="@Model.Actual!.NombreArtista" />
            <input type="hidden" asp-for="@Model.Actual!.Nacionalidad" />
        }

        @if (ViewData.ContainsKey("Mensaje"))
        {
            <input type="hidden" asp-for="@Model.Accion" />
            <div class="alert alert-info alert-dismissible fade show shadow-sm" role="alert">
                @await Html.PartialAsync("../Emergentes/Mensajes.cshtml")
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
        }

        @if (Model.Accion == lib_dominio.Nucleo.Enumerables.Ventanas.Editar)
        {
            <div class="card card-custom">
                <div class="card-header-custom">
                    <span><i class="fas fa-edit me-2"></i>Información del Artista</span>
                </div>
                <div class="card-body-custom">
                    <div class="row g-3">
                        <div class="col-md-6">
                            <label class="form-label fw-bold">Nombre del Artista</label>
                            <input class="form-control" asp-for="@Model.Actual!.NombreArtista" placeholder="Ej. Maluma" />
                            <span asp-validation-for="@Model.Actual!.NombreArtista" class="text-danger"></span>
                        </div>

                        <div class="col-md-6">
                            <label class="form-label fw-bold">Nacionalidad</label>
                            <input class="form-control" asp-for="@Model.Actual!.Nacionalidad" placeholder="Ej. Colombia" />
                            <span asp-validation-for="@Model.Actual!.Nacionalidad" class="text-danger"></span>

							<div class="col-md-6">
								<label class="form-label fw-bold">Imagen (URL)</label>
								<input class="form-control" asp-for="@Model.Actual!.Imagen" placeholder="https://..." />
							</div>

							@if (!string.IsNullOrEmpty(Model.Actual!.Imagen))
							{
								<div class="col-md-6 text-center">
									<label class="form-label fw-bold">Vista previa</label><br />
									<img src="@Model.Actual.Imagen" class="img-thumbnail" style="max-height:150px;" />
								</div>
							}

                        </div>

                    </div>
                </div>
            </div>
        }

        @if (Model.Accion == lib_dominio.Nucleo.Enumerables.Ventanas.Borrar)
        {
            <div class="modal-overlay">
                <div class="modal-content-custom text-center">
                    <div class="mb-3 text-danger">
                        <i class="fas fa-exclamation-triangle fa-3x"></i>
                    </div>
                    <h3>¿Eliminar Producto?</h3>
                    <p class="text-muted">Esta acción no se puede deshacer.</p>

                    <div class="alert alert-warning">
                        <strong>@Model.Actual!.NombreArtista</strong>
                    </div>

                    <div class="d-flex justify-content-center gap-3 mt-4">
                        <button type="submit" asp-page-handler="BtBorrar" class="btn btn-danger px-4">
                            <i class="fas fa-trash-alt me-2"></i>Confirmar Borrar
                        </button>
                        <button type="submit" asp-page-handler="BtCancelar" class="btn btn-light px-4 border">
                            Cancelar
                        </button>
                    </div>
                </div>
            </div>
        }

        @if (Model.Accion == lib_dominio.Nucleo.Enumerables.Ventanas.Listas ||
                Model.Accion == lib_dominio.Nucleo.Enumerables.Ventanas.Borrar)
        {
            <div class="card card-custom">
                <div class="card-header-custom">
                    <span><i class="fas fa-list me-2"></i>Listado de Artistas</span>
                </div>
                <div class="card-body-custom">

                    <div class="row g-2 mb-4 p-3 bg-light rounded">
                        <div class="col-md-5">
                            <div class="input-group">
                                <span class="input-group-text bg-white"><i class="fas fa-filter"></i></span>
                                <input class="form-control" asp-for="@Model.Filtro!.NombreArtista" placeholder="Filtrar por Nombre del Artista..." />
                            </div>
                        </div>

                        <div class="col-md-2">
                            <button type="submit" asp-page-handler="BtRefrescar" class="btn btn-primary w-100">
                                <i class="fas fa-search"></i> Buscar
                            </button>
                        </div>
                    </div>

                    <div class="table-responsive">
                        <table class="table table-custom align-middle">
							<thead>
								<tr>
									<th>Imagen</th>
									<th>Artista</th>
									<th>Nacionalidad</th>
									<th class="text-end">Acciones</th>
								</tr>
							</thead>

                            <tbody>
                                @if (Model != null && Model.Lista != null && Model.Lista.Any())
                                {
                                    @foreach (var elemento in Model.Lista)
                                    {
                                        <tr>
											<td>
												@if (!string.IsNullOrEmpty(elemento.Imagen))
												{
													<img src="@elemento.Imagen" width="70" class="rounded" />
												}
												else
												{
													<span class="text-muted">Sin imagen</span>
												}
											</td>
                                            <td class="fw-bold">@elemento.NombreArtista</td>
                                            <td class="fw-bold">@elemento.Nacionalidad</td>
                                            <td class="text-end">
                                                <button type="submit" asp-page-handler="BtModificar" asp-route-data="@elemento.ArtistaId"
                                                        class="btn btn-sm btn-warning text-white" title="Editar">
                                                    <i class="fas fa-pen"></i>
                                                </button>
                                                <button type="submit" asp-page-handler="BtBorrarVal" asp-route-data="@elemento.ArtistaId"
                                                        class="btn btn-sm btn-danger" title="Borrar">
                                                    <i class="fas fa-trash"></i>
                                                </button>
                                            </td>
                                        </tr>
                                    }
                                }
                                else
                                {
                                    <tr>
                                        <td colspan="7" class="text-center py-4 text-muted">
                                            <i class="fas fa-inbox fa-2x mb-2"></i><br>
                                            No hay Artistas registrados
                                        </td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        }
    </form>
</div>

asp_presentacion/Pages/Ventanas/DetallePedidos.cshtml
@page
@model asp_presentacion.Pages.Ventanas.DetallePedidosModel
@{
    ViewData["Titulo"] = "Gestión de Detalles de pedidos";
}

<div class="container-fluid py-4">
    <form method="POST" enctype="multipart/form-data">
        @Html.AntiForgeryToken()

        <div class="d-flex justify-content-between align-items-center page-header">
            <h2 class="text-primary mb-0"><i class="fas fa-list-ul"></i>Detalles de los pedidos</h2>

            <div class="action-bar">
                <button type="submit" asp-page-handler="BtRefrescar"
                        class="btn btn-outline-primary btn-icon"
                        disabled="@(Model.Accion != lib_dominio.Nucleo.Enumerables.Ventanas.Listas)">
                    <i class="fas fa-sync-alt"></i> Refrescar
                </button>

                <button type="submit" asp-page-handler="BtNuevo"
                        class="btn btn-success btn-icon"
                        disabled="@(Model.Accion != lib_dominio.Nucleo.Enumerables.Ventanas.Listas)">
                    <i class="fas fa-plus"></i> Nuevo
                </button>

                <button type="submit" asp-page-handler="BtGuardar"
                        class="btn btn-primary btn-icon"
                        disabled="@(Model.Accion == lib_dominio.Nucleo.Enumerables.Ventanas.Listas)">
                    <i class="fas fa-save"></i> Guardar
                </button>

                <button type="submit" asp-page-handler="BtCancelar"
                        class="btn btn-secondary btn-icon"
                        disabled="@(Model.Accion == lib_dominio.Nucleo.Enumerables.Ventanas.Listas)">
                    <i class="fas fa-times"></i> Cancelar
                </button>
            </div>
        </div>

        @if (Model.Accion != lib_dominio.Nucleo.Enumerables.Ventanas.Listas ||
                Model.Accion == lib_dominio.Nucleo.Enumerables.Ventanas.Borrar)
        {
            <input type="hidden" asp-for="@Model.Actual!.DetallesId" />
        }
        @if (Model.Accion == lib_dominio.Nucleo.Enumerables.Ventanas.Borrar)
        {
            <input type="hidden" asp-for="@Model.Actual!.cantidad" />
            <input type="hidden" asp-for="@Model.Actual!.PrecioUnitario" />
        }

        @if (ViewData.ContainsKey("Mensaje"))
        {
            <input type="hidden" asp-for="@Model.Accion" />
            <div class="alert alert-info alert-dismissible fade show shadow-sm" role="alert">
                @await Html.PartialAsync("../Emergentes/Mensajes.cshtml")
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
        }

        @if (Model.Accion == lib_dominio.Nucleo.Enumerables.Ventanas.Editar)
        {
            <div class="card card-custom">
                <div class="card-header-custom">
                    <span><i class="fas fa-edit me-2"></i>Información de los detalles</span>
                </div>
                <div class="card-body-custom">
                    <div class="row g-3">
                        <div class="col-md-6">
                            <label class="form-label fw-bold">Cantidad</label>
                            <input class="form-control" asp-for="@Model.Actual!.cantidad" placeholder="Ej. 12, 2, 3, 5" />
                            <span asp-validation-for="@Model.Actual!.cantidad" class="text-danger"></span>
                        </div>

                        <div class="col-md-4">
                            <label class="form-label fw-bold">Precio unitario</label>
                            <div class="input-group">
                                <span class="input-group-text">$</span>
                                <input class="form-control" asp-for="@Model.Actual!.PrecioUnitario" type="number" step="0.01" />
                            </div>
                        </div>

                    </div>
                </div>
            </div>
        }

        @if (Model.Accion == lib_dominio.Nucleo.Enumerables.Ventanas.Borrar)
        {
            <div class="modal-overlay">
                <div class="modal-content-custom text-center">
                    <div class="mb-3 text-danger">
                        <i class="fas fa-exclamation-triangle fa-3x"></i>
                    </div>
                    <h3>¿Eliminar Producto?</h3>
                    <p class="text-muted">Esta acción no se puede deshacer.</p>

                    <div class="alert alert-warning">
                        <strong>@Model.Actual!.cantidad</strong>
                    </div>

                    <div class="d-flex justify-content-center gap-3 mt-4">
                        <button type="submit" asp-page-handler="BtBorrar" class="btn btn-danger px-4">
                            <i class="fas fa-trash-alt me-2"></i>Confirmar Borrar
                        </button>
                        <button type="submit" asp-page-handler="BtCancelar" class="btn btn-light px-4 border">
                            Cancelar
                        </button>
                    </div>
                </div>
            </div>
        }

        @if (Model.Accion == lib_dominio.Nucleo.Enumerables.Ventanas.Listas ||
                Model.Accion == lib_dominio.Nucleo.Enumerables.Ventanas.Borrar)
        {
            <div class="card card-custom">
                <div class="card-header-custom">
                    <span><i class="fas fa-list me-2"></i>Listado de DetallePedidos</span>
                </div>
                <div class="card-body-custom">

                    <div class="table-responsive">
                        <table class="table table-custom align-middle">
                            <thead>
                                <tr>
                                    <th>Cantidad</th>
                                    <th>Precio unitario</th>
                                    <th class="text-end">Acciones</th>
                                </tr>
                            </thead>
                            <tbody>
                                @if (Model != null && Model.Lista != null && Model.Lista.Any())
                                {
                                    @foreach (var elemento in Model.Lista)
                                    {
                                        <tr>
                                            <td class="fw-bold">@elemento.cantidad</td>
                                            <td class="text-success fw-bold">@elemento.PrecioUnitario.ToString("C")</td>
                                            <td class="text-end">
                                                <button type="submit" asp-page-handler="BtModificar" asp-route-data="@elemento.DetallesId"
                                                        class="btn btn-sm btn-warning text-white" title="Editar">
                                                    <i class="fas fa-pen"></i>
                                                </button>
                                                <button type="submit" asp-page-handler="BtBorrarVal" asp-route-data="@elemento.DetallesId"
                                                        class="btn btn-sm btn-danger" title="Borrar">
                                                    <i class="fas fa-trash"></i>
                                                </button>
                                            </td>
                                        </tr>
                                    }
                                }
                                else
                                {
                                    <tr>
                                        <td colspan="7" class="text-center py-4 text-muted">
                                            <i class="fas fa-inbox fa-2x mb-2"></i><br>
                                            No hay DetallePedidos registrados
                                        </td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        }
    </form>
</div>